# Generated by Django 2.2.4 on 2019-12-12 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('img', models.ImageField(upload_to='img/')),
                ('title', models.CharField(max_length=100)),
                ('title2', models.CharField(max_length=100)),
                ('title3', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField(auto_now_add=True)),
                ('event_hotel', models.CharField(default='edit', max_length=100)),
                ('event_country', models.CharField(default='edit', max_length=100)),
                ('heading1', models.CharField(max_length=100)),
                ('body1', models.TextField()),
                ('heading2', models.CharField(max_length=100)),
                ('body2', models.TextField()),
                ('heading3', models.CharField(max_length=100)),
                ('body3', models.TextField()),
            ],
        ),
    ]
