# Generated by Django 2.2.4 on 2019-12-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='name1',
            field=models.CharField(default='speaker name', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='name2',
            field=models.CharField(default='speaker name', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='name3',
            field=models.CharField(default='speaker name', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='name4',
            field=models.CharField(default='speaker name', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='name5',
            field=models.CharField(default='speaker name', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='name6',
            field=models.CharField(default='speaker name', max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='speaker1',
            field=models.ImageField(default='http://via.placeholder.com/200', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='article',
            name='speaker2',
            field=models.ImageField(default='http://via.placeholder.com/200', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='article',
            name='speaker3',
            field=models.ImageField(default='http://via.placeholder.com/200', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='article',
            name='speaker4',
            field=models.ImageField(default='http://via.placeholder.com/200', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='article',
            name='speaker5',
            field=models.ImageField(default='http://via.placeholder.com/200', upload_to='img/'),
        ),
        migrations.AddField(
            model_name='article',
            name='speaker6',
            field=models.ImageField(default='http://via.placeholder.com/200', upload_to='img/'),
        ),
    ]
