# Generated by Django 2.2.4 on 2019-12-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_article2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article2',
            old_name='Title',
            new_name='event_title',
        ),
        migrations.AddField(
            model_name='article2',
            name='title',
            field=models.CharField(default='edit', max_length=100),
        ),
    ]
