# Generated by Django 2.2.4 on 2019-12-18 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191218_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeakerImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker_img', models.ImageField(default='http://via.placeholder.com/200', upload_to='img/')),
                ('speaker_name', models.CharField(default='speaker name', max_length=50)),
                ('title', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Article2')),
            ],
        ),
    ]
