# Generated by Django 2.2.4 on 2019-12-19 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_speakerimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article2',
            name='slug',
            field=models.SlugField(default='edit'),
        ),
        migrations.AlterField(
            model_name='speakerimg',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Article'),
        ),
    ]
