# Generated by Django 2.2.4 on 2019-12-19 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_speakerimg_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerimg',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Article2'),
        ),
    ]
