# Generated by Django 2.2.4 on 2019-12-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_speakerimg_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerimg',
            name='speaker_title',
            field=models.CharField(default='title', max_length=100),
        ),
    ]
