# Generated by Django 2.2.4 on 2019-12-19 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20191219_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_title', models.CharField(default='title', max_length=100)),
                ('sponsor_img', models.ImageField(default='http://via.placeholder.com/200', upload_to='img/')),
                ('sponsor_name', models.CharField(default='speaker name', max_length=50)),
                ('slug', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.Article2')),
            ],
        ),
    ]
